spring:
#  profiles:
#    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3366/db_resto_local_server
    username: root
    password: restosuite

mybatis:
  mapper-locations: classpath*:com/use/demo/mappers/*Mapper.xml

mybatis-plus:
  mapper-locations: classpath*:com/use/demo/mappers/*Mapper.xml
